# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/overlay_32x16/overlay_32x16.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16 || ORIG_REF_NAME==overlay_32x16} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_zynq_ultra_ps_e_0_0/overlay_32x16_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==overlay_32x16_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_proc_sys_reset_0_0/overlay_32x16_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_proc_sys_reset_0_0 || ORIG_REF_NAME==overlay_32x16_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_xlconcat_0_0/overlay_32x16_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_xlconcat_0_0 || ORIG_REF_NAME==overlay_32x16_xlconcat_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_smartconnect_0_0/overlay_32x16_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_smartconnect_0_0 || ORIG_REF_NAME==overlay_32x16_smartconnect_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_smartconnect_1_0/overlay_32x16_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_smartconnect_1_0 || ORIG_REF_NAME==overlay_32x16_smartconnect_1_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_axi_dma_0_0/overlay_32x16_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_axi_dma_0_0 || ORIG_REF_NAME==overlay_32x16_axi_dma_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_axis_dwidth_converter_0_0/overlay_32x16_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_axis_dwidth_converter_0_0 || ORIG_REF_NAME==overlay_32x16_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/overlay_32x16/ip/overlay_32x16_addone_32x16_0_0/overlay_32x16_addone_32x16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_32x16_addone_32x16_0_0 || ORIG_REF_NAME==overlay_32x16_addone_32x16_0_0} -quiet] -quiet

# XDC: bd/overlay_32x16/overlay_32x16_ooc.xdc
