# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/overlay_8x16_smartconnect_0_0.xci
# IP: The module: 'overlay_8x16_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/bd_d56b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_0/bd_d56b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_2/bd_d56b_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_3/bd_d56b_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_4/bd_d56b_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_5/bd_d56b_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_6/bd_d56b_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_7/bd_d56b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_8/bd_d56b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_9/bd_d56b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_10/bd_d56b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_11/bd_d56b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_12/bd_d56b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_13/bd_d56b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_14/bd_d56b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_15/bd_d56b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_16/bd_d56b_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_17/bd_d56b_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_18/bd_d56b_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_19/bd_d56b_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_20/bd_d56b_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_21/bd_d56b_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_22/bd_d56b_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_23/bd_d56b_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_24/bd_d56b_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_25/bd_d56b_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_26/bd_d56b_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_27/bd_d56b_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_28/bd_d56b_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_29/bd_d56b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_30/bd_d56b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_31/bd_d56b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_32/bd_d56b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_33/bd_d56b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_34/bd_d56b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_35/bd_d56b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_2/bd_d56b_arsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_3/bd_d56b_rsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_4/bd_d56b_awsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_5/bd_d56b_wsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_6/bd_d56b_bsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_10/bd_d56b_s00a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_11/bd_d56b_sarn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_12/bd_d56b_srn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_13/bd_d56b_sawn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_14/bd_d56b_swn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_15/bd_d56b_sbn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_19/bd_d56b_s01a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_20/bd_d56b_sarn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_21/bd_d56b_srn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_25/bd_d56b_s02a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_26/bd_d56b_sawn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_27/bd_d56b_swn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_28/bd_d56b_sbn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_29/bd_d56b_m00s2a_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_30/bd_d56b_m00arn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_31/bd_d56b_m00rn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_32/bd_d56b_m00awn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_33/bd_d56b_m00wn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_34/bd_d56b_m00bn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x16_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/overlay_8x16_smartconnect_0_0.xci
# IP: The module: 'overlay_8x16_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/bd_d56b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_0/bd_d56b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_2/bd_d56b_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_3/bd_d56b_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_4/bd_d56b_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_5/bd_d56b_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_6/bd_d56b_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_7/bd_d56b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_8/bd_d56b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_9/bd_d56b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_10/bd_d56b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_11/bd_d56b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_12/bd_d56b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_13/bd_d56b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_14/bd_d56b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_15/bd_d56b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_16/bd_d56b_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_17/bd_d56b_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_18/bd_d56b_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_19/bd_d56b_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_20/bd_d56b_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_21/bd_d56b_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_22/bd_d56b_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_23/bd_d56b_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_24/bd_d56b_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_25/bd_d56b_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_26/bd_d56b_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_27/bd_d56b_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_28/bd_d56b_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_29/bd_d56b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_30/bd_d56b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_31/bd_d56b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_32/bd_d56b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_33/bd_d56b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_34/bd_d56b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_35/bd_d56b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_1/bd_d56b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_2/bd_d56b_arsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_3/bd_d56b_rsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_4/bd_d56b_awsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_5/bd_d56b_wsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_6/bd_d56b_bsw_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_10/bd_d56b_s00a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_11/bd_d56b_sarn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_12/bd_d56b_srn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_13/bd_d56b_sawn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_14/bd_d56b_swn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_15/bd_d56b_sbn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_19/bd_d56b_s01a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_20/bd_d56b_sarn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_21/bd_d56b_srn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_25/bd_d56b_s02a2s_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_26/bd_d56b_sawn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_27/bd_d56b_swn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_28/bd_d56b_sbn_1_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_29/bd_d56b_m00s2a_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_30/bd_d56b_m00arn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_31/bd_d56b_m00rn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_32/bd_d56b_m00awn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_33/bd_d56b_m00wn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/bd_0/ip/ip_34/bd_d56b_m00bn_0_ooc.xdc

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x16_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
