# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/overlay_8x32_smartconnect_1_0.xci
# IP: The module: 'overlay_8x32_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/bd_9c02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_0/bd_9c02_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_2/bd_9c02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_3/bd_9c02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_4/bd_9c02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_5/bd_9c02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_6/bd_9c02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_7/bd_9c02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_8/bd_9c02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_9/bd_9c02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_10/bd_9c02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_11/bd_9c02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_12/bd_9c02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_5/bd_9c02_s00a2s_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_6/bd_9c02_sarn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_7/bd_9c02_srn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_8/bd_9c02_sawn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_9/bd_9c02_swn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_10/bd_9c02_sbn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_11/bd_9c02_m00s2a_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x32_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/overlay_8x32_smartconnect_1_0.xci
# IP: The module: 'overlay_8x32_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/bd_9c02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_0/bd_9c02_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_2/bd_9c02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_3/bd_9c02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_4/bd_9c02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_5/bd_9c02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_6/bd_9c02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_7/bd_9c02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_8/bd_9c02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_9/bd_9c02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_10/bd_9c02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_11/bd_9c02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_12/bd_9c02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_1/bd_9c02_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_5/bd_9c02_s00a2s_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_6/bd_9c02_sarn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_7/bd_9c02_srn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_8/bd_9c02_sawn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_9/bd_9c02_swn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_10/bd_9c02_sbn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/bd_0/ip/ip_11/bd_9c02_m00s2a_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_8x32/overlay_8x32/overlay_8x32.srcs/sources_1/bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x32_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
