# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0.xci
# IP: The module: 'overlay_32x32_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0.xci
# IP: The module: 'overlay_32x32_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_proc_sys_reset_0_0/overlay_32x32_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
