# Usage:
# MAKE targets:
#       generator:              create Halide generator

###############################################################################
# MODIFICATION: NONE
#------------------------------------------------------------------------------
# Makefile parameter/variable declarations
#
###############################################################################

include ../../build-files/Makefile.defs.inc



###############################################################################
# MODIFICATION: OPTIONAL
#------------------------------------------------------------------------------
# App-specific info
#
# TESTNAME                      : name of the app
# USE_CORE_IR_VALID             : whether to generate valid signal for coreir codegen
# HL_TARGET                     : Halide target
# RDAI_PLATFORM_RUNTIME         : RDAI platform runtime to use 
###############################################################################

TESTNAME                        = conv_3_3
HL_TARGET						= arm-64-linux

###############################################################################
# MODIFICATION : NONE
#------------------------------------------------------------------------------
# Include hardware build targets
#
###############################################################################

include ../../build-files/Makefile.targets.inc


