# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_addone_8x16_0_0/overlay_8x16_addone_8x16_0_0.xci
# IP: The module: 'overlay_8x16_addone_8x16_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_addone_8x16_0_0/constraints/hls_target_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x16_addone_8x16_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_addone_8x16_0_0/overlay_8x16_addone_8x16_0_0.xci
# IP: The module: 'overlay_8x16_addone_8x16_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charles/Documents/2020_REU/vivado_script_dev/overlay_8x16/overlay_8x16/overlay_8x16.srcs/sources_1/bd/overlay_8x16/ip/overlay_8x16_addone_8x16_0_0/constraints/hls_target_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_8x16_addone_8x16_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
