# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/overlay_8x32/overlay_8x32.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32 || ORIG_REF_NAME==overlay_8x32} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_zynq_ultra_ps_e_0_0/overlay_8x32_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==overlay_8x32_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_proc_sys_reset_0_0/overlay_8x32_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_proc_sys_reset_0_0 || ORIG_REF_NAME==overlay_8x32_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_xlconcat_0_0/overlay_8x32_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_xlconcat_0_0 || ORIG_REF_NAME==overlay_8x32_xlconcat_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_smartconnect_0_0/overlay_8x32_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_smartconnect_0_0 || ORIG_REF_NAME==overlay_8x32_smartconnect_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_smartconnect_1_0/overlay_8x32_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_smartconnect_1_0 || ORIG_REF_NAME==overlay_8x32_smartconnect_1_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_axi_dma_0_0/overlay_8x32_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_axi_dma_0_0 || ORIG_REF_NAME==overlay_8x32_axi_dma_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_addone_8x32_0_0/overlay_8x32_addone_8x32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_addone_8x32_0_0 || ORIG_REF_NAME==overlay_8x32_addone_8x32_0_0} -quiet] -quiet

# IP: bd/overlay_8x32/ip/overlay_8x32_axis_dwidth_converter_0_0/overlay_8x32_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==overlay_8x32_axis_dwidth_converter_0_0 || ORIG_REF_NAME==overlay_8x32_axis_dwidth_converter_0_0} -quiet] -quiet

# XDC: bd/overlay_8x32/overlay_8x32_ooc.xdc
