# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/overlay_32x32_smartconnect_1_0.xci
# IP: The module: 'overlay_32x32_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/bd_7751.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_0/bd_7751_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_2/bd_7751_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_3/bd_7751_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_4/bd_7751_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_5/bd_7751_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_6/bd_7751_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_7/bd_7751_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_8/bd_7751_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_9/bd_7751_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_10/bd_7751_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_11/bd_7751_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_12/bd_7751_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_5/bd_7751_s00a2s_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_6/bd_7751_sarn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_7/bd_7751_srn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_8/bd_7751_sawn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_9/bd_7751_swn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_10/bd_7751_sbn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_11/bd_7751_m00s2a_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/overlay_32x32_smartconnect_1_0.xci
# IP: The module: 'overlay_32x32_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/bd_7751.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_0/bd_7751_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_2/bd_7751_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_3/bd_7751_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_4/bd_7751_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_5/bd_7751_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_6/bd_7751_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_7/bd_7751_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_8/bd_7751_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_9/bd_7751_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_10/bd_7751_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_11/bd_7751_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_12/bd_7751_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_1/bd_7751_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_5/bd_7751_s00a2s_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_6/bd_7751_sarn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_7/bd_7751_srn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_8/bd_7751_sawn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_9/bd_7751_swn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_10/bd_7751_sbn_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/bd_0/ip/ip_11/bd_7751_m00s2a_0_ooc.xdc

# XDC: /home/charles/tmp/vivado_script_dev/overlay_32x32/overlay_32x32/overlay_32x32.srcs/sources_1/bd/overlay_32x32/ip/overlay_32x32_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'overlay_32x32_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
