# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.runs/synth_1/conv_3_3_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.cache/wt [current_project]
set_property parent.project_path /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.5 [current_project]
set_property ip_repo_paths /home/nyengele/aha/fpga_builder/apps/conv_3_3/bin/fpga/hls/conv_3_3/conv_3_3/impl/ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/hdl/conv_3_3_wrapper.v
add_files /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/conv_3_3.bd
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/constraints/unoptimized_conv_3_3_rdai_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_axi_dma_0_0/conv_3_3_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_axi_dma_0_0/conv_3_3_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_axi_dma_0_0/conv_3_3_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_axis_dwidth_converter_0_0/conv_3_3_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_axis_dwidth_converter_1_0/conv_3_3_axis_dwidth_converter_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_proc_sys_reset_0_0/conv_3_3_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_proc_sys_reset_0_0/conv_3_3_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_proc_sys_reset_0_0/conv_3_3_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_1/bd_6d5f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_1/bd_6d5f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_2/bd_6d5f_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_3/bd_6d5f_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_4/bd_6d5f_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_5/bd_6d5f_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_6/bd_6d5f_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_10/bd_6d5f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_11/bd_6d5f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_12/bd_6d5f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_13/bd_6d5f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_14/bd_6d5f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_15/bd_6d5f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_19/bd_6d5f_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_20/bd_6d5f_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_21/bd_6d5f_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_25/bd_6d5f_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_26/bd_6d5f_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_27/bd_6d5f_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_28/bd_6d5f_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_29/bd_6d5f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_30/bd_6d5f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_31/bd_6d5f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_32/bd_6d5f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_33/bd_6d5f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/bd_0/ip/ip_34/bd_6d5f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_1/bd_ad0e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_1/bd_ad0e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_5/bd_ad0e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_6/bd_ad0e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_7/bd_ad0e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_8/bd_ad0e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_9/bd_ad0e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_10/bd_ad0e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/bd_0/ip/ip_11/bd_ad0e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_zynq_ultra_ps_e_0_0/conv_3_3_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_zynq_ultra_ps_e_0_0/conv_3_3_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/conv_3_3_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top conv_3_3_wrapper -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef conv_3_3_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file conv_3_3_wrapper_utilization_synth.rpt -pb conv_3_3_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
