# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/conv_3_3/conv_3_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3 || ORIG_REF_NAME==conv_3_3} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/conv_3_3_conv_3_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_conv_3_3_0_0 || ORIG_REF_NAME==conv_3_3_conv_3_3_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_axi_dma_0_0/conv_3_3_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_axi_dma_0_0 || ORIG_REF_NAME==conv_3_3_axi_dma_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_axis_dwidth_converter_0_0/conv_3_3_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_axis_dwidth_converter_0_0 || ORIG_REF_NAME==conv_3_3_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_axis_dwidth_converter_1_0/conv_3_3_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_axis_dwidth_converter_1_0 || ORIG_REF_NAME==conv_3_3_axis_dwidth_converter_1_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_proc_sys_reset_0_0/conv_3_3_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_proc_sys_reset_0_0 || ORIG_REF_NAME==conv_3_3_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_smartconnect_0_0/conv_3_3_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_smartconnect_0_0 || ORIG_REF_NAME==conv_3_3_smartconnect_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_smartconnect_1_0/conv_3_3_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_smartconnect_1_0 || ORIG_REF_NAME==conv_3_3_smartconnect_1_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_xlconcat_0_0/conv_3_3_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_xlconcat_0_0 || ORIG_REF_NAME==conv_3_3_xlconcat_0_0} -quiet] -quiet

# IP: bd/conv_3_3/ip/conv_3_3_zynq_ultra_ps_e_0_0/conv_3_3_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_3_3_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==conv_3_3_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/conv_3_3/conv_3_3_ooc.xdc
