# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/conv_3_3_conv_3_3_0_0.xci
# IP: The module: 'conv_3_3_conv_3_3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/constraints/unoptimized_conv_3_3_rdai_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_3_3_conv_3_3_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/conv_3_3_conv_3_3_0_0.xci
# IP: The module: 'conv_3_3_conv_3_3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nyengele/aha/fpga_builder/apps/conv_3_3/conv_3_3/conv_3_3.srcs/sources_1/bd/conv_3_3/ip/conv_3_3_conv_3_3_0_0/constraints/unoptimized_conv_3_3_rdai_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_3_3_conv_3_3_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
